; This file was auto-generated by drush make
core = 7.x
api  = 2

; Core
projects[drupal][version]                = "7.44"

; Contrib
projects[admin_menu][subdir]             = "contrib"
projects[admin_menu][version]            = "3.0-rc5"

projects[admin_views][subdir]            = "contrib"
projects[admin_views][version]           = "1.5"

projects[apachesolr][subdir]             = "contrib"
projects[apachesolr][version]            = "1.8"

projects[apachesolr_multilingual][subdir]   = "contrib"
projects[apachesolr_multilingual][version]  = "1.3"

projects[apachesolr_attachments][subdir]    = "contrib"
projects[apachesolr_attachments][version]   = "1.4"

projects[apachesolr_multisitesearch][subdir]  = "contrib"
projects[apachesolr_multisitesearch][version] = "1.1"

projects[autologout][subdir]             = "contrib"
projects[autologout][version]            = "4.4"

projects[bean][subdir]                   = "contrib"
projects[bean][version]                  = "1.9"

projects[blockreference][subdir]         = "contrib"
projects[blockreference][version]        = "2.2"

projects[ckeditor][subdir]               = "contrib"
projects[ckeditor][version]              = "1.17"

projects[content_menu][subdir]           = "contrib"
projects[content_menu][version]          = "1.0"

projects[context][subdir]                = "contrib"
projects[context][version]               = "3.6"

projects[context_entity_field][subdir]   = "contrib"
projects[context_entity_field][version]  = "1.1"

projects[ctools][subdir]                 = "contrib"
projects[ctools][version]                = "1.9"

projects[date][subdir]                   = "contrib"
projects[date][version]                  = "2.9"
projects[date][patch][]        ="https://www.drupal.org/files/issues/calendar_pager_broken-2375235-35.patch"

projects[drafty][subdir]                 = "contrib"
projects[drafty][version]                = "1.0-beta2"
projects[drafty][patch][]                = "../data/patch/drafty/drafty-dev-version-4cdfe95bff8c703c1ee216bf7b80ac1c2c6adfc8.patch"
projects[drafty][patch][]                = "https://www.drupal.org/files/issues/drafty-2429427.patch"

projects[elysia_cron][subdir]            = "contrib"
projects[elysia_cron][version]           = "2.1"

projects[entity][subdir]                 = "contrib"
projects[entity][version]                = "1.6"

projects[entityreference][subdir]        = "contrib"
projects[entityreference][version]       = "1.1"

projects[entity_translation][subdir]     = "contrib"
projects[entity_translation][version]    = "1.0-beta5"

projects[eu_cookie_compliance][subdir]   = "contrib"
projects[eu_cookie_compliance][version]  = "1.14"

projects[features][subdir]               = "contrib"
projects[features][version]              = "2.10"

projects[field_validation][subdir]       = "contrib"
projects[field_validation][version]      = "2.6"

projects[globalredirect][subdir]         = "contrib"
projects[globalredirect][version]        = "1.5"
projects[globalredirect][patch][]        = "../data/patch/global_redirect/global_redirect_quickfix.patch"

projects[google_analytics][subdir]       = "contrib"
projects[google_analytics][version]      = "2.1"

projects[google_tag][subdir]             = "contrib"
projects[google_tag][version]            = "1.0"
; see: https://www.drupal.org/node/2431109#comment-10416503
projects[google_tag][patch][]            = "https://www.drupal.org/files/issues/google_tag-corrected_translatable_string-2431109-2.patch"

projects[honeypot][subdir]               = "contrib"
projects[honeypot][version]              = "1.21"

projects[htmlmail][subdir]               = "contrib"
projects[htmlmail][version]              = "2.65"
; see: https://www.drupal.org/node/1692966#comment-6251940
projects[htmlmail][patch][]              = "https://www.drupal.org/files/1692966-htmlmail-mailsystem-html-to-text.patch"

projects[i18n][subdir]                   = "contrib"
projects[i18n][version]                  = "1.13"

projects[i18n_menu_overview][subdir]     = "contrib"
projects[i18n_menu_overview][version]    = "3.23"

projects[imagecache_actions][subdir]     = "contrib"
projects[imagecache_actions][version]    = "1.5"
projects[imagecache_actions][patch][]    = "../data/patch/imagecache_actions/imagecache_actions-dev-version-d6a9760aa85c64b8345b46f8c1b6ab763c1dae6b.patch"

projects[interactive_image][subdir]      = "contrib"
projects[interactive_image][download][type] = "git"
projects[interactive_image][download][url] = "https://git.drupal.org/sandbox/ravi_sam/1279962.git"
projects[interactive_image][download][branch] = "7.x-1.x"
projects[interactive_image][download][revision] = "d81df47aa365e10986dc4a9ae292057c59b1123d"
projects[interactive_image][patch][]     = "https://www.drupal.org/files/issues/add-user-icon-support-2657602-1.patch"
projects[interactive_image][patch][]     = "https://www.drupal.org/files/issues/resolve-core-deps-1279962-1.patch"
projects[interactive_image][patch][]     = "https://www.drupal.org/files/issues/undefined-index-fix-2662720-1.patch"
projects[interactive_image][patch][]     = "https://www.drupal.org/files/issues/image-loads-consistently-2390085-2.patch"
projects[interactive_image][patch][]     = "https://www.drupal.org/files/issues/2657602-add-other-icons-5.patch"

projects[jquery_update][subdir]          = "contrib"
projects[jquery_update][version]         = "2.7"

projects[language_fallback][subdir]      = "contrib"
projects[language_fallback][version]     = "1.0"
projects[language_fallback][patch][]     = "../data/patch/language_fallback/language_fallback-dev-version-1fa8e63e43f496e23a18309242a9076f0cc2d28d.patch"

projects[l10n_update][subdir]            = "contrib"
projects[l10n_update][version]           = "2.0"

projects[libraries][subdir]              = "contrib"
projects[libraries][version]             = "2.2"

projects[link][subdir]                   = "contrib"
projects[link][version]                  = "1.4"

projects[mailsystem][subdir]             = "contrib"
projects[mailsystem][version]            = "3.0-alpha1"
projects[mailsystem][patch][]            = "../data/patch/mailsystem/mailsystem-dev-version-4c957ae4c422e0d3ab70ef7b7fd0b4cad65fea51.patch"

projects[manualcrop][subdir]             = "contrib"
projects[manualcrop][version]            = "1.5"

projects[menuimage][subdir]              = "contrib"
projects[menuimage][version]             = "1.1"

projects[menu_reference][subdir]         = "contrib"
projects[menu_reference][version]        = "1.2"

projects[menu_target][subdir]            = "contrib"
projects[menu_target][version]           = "1.4"

projects[message][subdir]                = "contrib"
; see https://www.drupal.org/node/2620280#comment-10634936
; see https://blog.engineyard.com/2015/what-to-expect-php-7
projects[message][version]               = "1.11"

projects[message_notify][subdir]         = "contrib"
projects[message_notify][version]        = "2.5"

projects[metatag][subdir]                = "contrib"
projects[metatag][version]               = "1.7"

projects[module_filter][subdir]          = "contrib"
projects[module_filter][version]         = "2.0"

projects[password_policy][subdir]        = "contrib"
projects[password_policy][version]       = "1.12"

projects[pathauto][subdir]               = "contrib"
projects[pathauto][version]              = "1.3"

projects[paragraphs][subdir]             = "contrib"
projects[paragraphs][version]            = "1.0-rc4"

projects[message_ui][subdir]             = "contrib"
projects[message_ui][version]            = "1.4"

; This patch combine with State_Machine generates side-effects.
; During the creation of a new translation, if the user publish directly the translation
; the data for the paragraph field are lost, after editing the same translation.
; Remove it, until its fix.
;projects[paragraphs][patch][]            = "https://www.drupal.org/files/issues/paragraphs_d7_entity_translation_fix_attempt.patch"
projects[paragraphs][patch][]            = "https://www.drupal.org/files/issues/paragraphs-State-flow-entity-paragraphs-deletion-2546762-2.patch"

projects[redirect][subdir]               = "contrib"
projects[redirect][version]              = "1.0-rc3"

projects[redis][subdir]                  = "contrib"
projects[redis][version]                 = "3.11"

projects[robotstxt][subdir]              = "contrib"
projects[robotstxt][version]             = "1.3"

projects[scald][subdir]                  = "contrib"
projects[scald][version]                 = "1.6"
projects[scald][patch][]                 = "../data/patch/scald/scald-mee-options-link.patch"
projects[scald][patch][]                 = "../data/patch/scald/scald-mee-empty-resource-manager.patch"
projects[scald][patch][]                 = "../data/patch/scald-audio-add-theme-hook-suggestions.patch"
projects[scald][patch][]                 = "../data/patch/scald/scald-atom-reference-field-formatter-keep-entity.patch"

projects[scald_file][subdir]             = "contrib"
projects[scald_file][version]            = "1.3"

projects[scald_text][subdir]             = "contrib"
projects[scald_file][version]            = "1.x-dev"

projects[securelogin][subdir]            = "contrib"
projects[securelogin][version]           = "1.5"

projects[security_review][subdir]        = "contrib"
projects[security_review][version]       = "1.2"

projects[services][subdir]               = "contrib"
projects[services][version]              = "3.13"

projects[sharethis][subdir]              = "contrib"
projects[sharethis][version]             = "2.12"

projects[smart_trim][subdir]             = "contrib"
projects[smart_trim][version]            = "1.5"
projects[smart_trim][patch][]            = "../data/patch/smart_trim/smart_trim-dev-version-5b185971a29fe3f8a1a580f88fc583f068419316.patch"
projects[smart_trim][patch][]            = "https://www.drupal.org/files/issues/smart_trim-7.x-1.x-html-with-content-link-2507161-6.patch"
projects[smart_trim][patch][]            = "../data/patch/smart_trim/smart_trim-7.x-1.x-allow-output-override.patch"

; issue regarding ApacheSolr module, see: https://www.drupal.org/node/2220535
projects[state_machine][subdir]          = "contrib"
projects[state_machine][version]         = "3.0-beta1"
;projects[state_machine][patch][]         = "../data/patch/state_machine/state-flow-entity-cached.patch"
;projects[state_machine][patch][]         = "https://www.drupal.org/files/issues/state_machine-node-revision-ET-switcher-2546728-4.patch"
;projects[state_machine][patch][]         = "https://www.drupal.org/files/issues/state_machine-node-revision-keep-primary-tabs-2546728-5.patch"
projects[state_machine][patch][]         = "../data/patch/state_machine/state-flow-node-admin-page.patch"
projects[state_machine][patch][]         = "../data/patch/state_machine/state-flow-entity-workflow.patch"
;projects[state_machine][patch][]         = "../data/patch/state_machine/state-flow-node-form-not-revision.patch"

projects[strongarm][subdir]              = "contrib"
projects[strongarm][version]             = "2.0"

projects[title][subdir]                  = "contrib"
projects[title][version]                 = "1.0-alpha7"
projects[title][patch][]                 = "../data/patch/title/title-dev-version-d6f2000bbf54686faccc95e7b970d7a00db1dfd8.patch"

projects[token][subdir]                  = "contrib"
projects[token][version]                 = "1.6"
projects[token][patch][]                 = "https://www.drupal.org/files/issues/token_field-description-all-types-1796024-22.patch"
projects[token][patch][]                 = "../data/patch/token/token-field_description-translation.patch"

projects[transliteration][subdir]        = "contrib"
projects[transliteration][version]       = "3.2"

projects[variable][subdir]               = "contrib"
projects[variable][version]              = "2.5"

projects[varnish][subdir]                = "contrib"
projects[varnish][version]               = "1.0-beta3"
projects[varnish][patch][]               = "https://www.drupal.org/files/issues/varnish-2371907-24.patch"

projects[views][subdir]                  = "contrib"
projects[views][version]                 = "3.11"

projects[views_accordion][subdir]        = "contrib"
projects[views_accordion][version]       = "1.1"

projects[views_bulk_operations][subdir]  = "contrib"
projects[views_bulk_operations][version] = "3.3"

projects[views_data_export][subdir]  = "contrib"
projects[views_data_export][version] = "3.1"

projects[webform][subdir]                = "contrib"
projects[webform][version]               = "4.11"

projects[webform_localization][subdir]   = "contrib"
projects[webform_localization][version]  = "4.3"
projects[webform_localization][patch][]  = "https://www.drupal.org/files/issues/field_labels_displayed_as_placeholders-2633228-18.patch"

projects[weight][subdir]                 = "contrib"
projects[weight][version]                = "2.5"

projects[xmlsitemap][subdir]             = "contrib"
projects[xmlsitemap][version]            = "2.3"

projects[google_adwords][subdir]         = "contrib"
projects[google_adwords][version]        = "2.1"
projects[google_adwords][patch][]        = "https://www.drupal.org/files/issues/2387723-1.patch"

projects[geolocation][subdir]            = "contrib"
projects[geolocation][version]           = "1.6"

projects[potx][subdir]                   = "contrib"
projects[potx][version]                  = "3.0-alpha2"

projects[field_group][subdir]         = "contrib"
projects[field_group][version]        = "1.5"

projects[multiple_selects][subdir]         = "contrib"
projects[multiple_selects][version]        = "1.2"

projects[better_exposed_filters][subdir]         = "contrib"
projects[better_exposed_filters][version]        = "3.2"

projects[breakpoints][subdir]            = "contrib"
projects[breakpoints][version]           = "1.4"

projects[picture][subdir]                = "contrib"
projects[picture][version]               = "2.13"

projects[intlinks][subdir]         = "contrib"
projects[intlinks][version]        = "2.0-alpha2"

projects[facetapi][subdir]            = "contrib"
projects[facetapi][version]           = "1.5"

projects[facetapi_i18n][subdir]            = "contrib"
projects[facetapi_i18n][version]           = "1.0-beta2"

projects[apachesolr_autocomplete][subdir] = "contrib"
projects[apachesolr_autocomplete][version] = "1.6"
projects[apachesolr_autocomplete][patch][] = "https://www.drupal.org/files/issues/default_counts-2656782_0.patch"

projects[migrate][subdir]        = "contrib"
projects[migrate][version]       = "2.8"

projects[migrate_extras][subdir]        = "contrib"
projects[migrate_extras][version]       = "2.5"

projects[calendar][subdir]         = "contrib"
projects[calendar][version]        = "3.5"

projects[node_clone][subdir]         = "contrib"
projects[node_clone][version]        = "1.0"

projects[mimemail][subdir]             = "contrib"
projects[mimemail][version]            = "1.0-beta4"

projects[replicate][subdir]         = "contrib"
projects[replicate][version]        = "1.1"

projects[replicate_ui][subdir]         = "contrib"
projects[replicate_ui][version]        = "1.5"

; Smile modules
projects[frontend_boost][type]           = "module"
projects[frontend_boost][subdir]         = "contrib"
projects[frontend_boost][version]        = "1.x"
projects[frontend_boost][download][type] = "git"
projects[frontend_boost][download][url]  = "http://gitlab.total.com/Smile/frontend_boost.git"
projects[frontend_boost][download][tag]  = 7.x-1.2

projects[smile_security][type]           = "module"
projects[smile_security][subdir]         = "contrib"
projects[smile_security][version]        = "1.x"
projects[smile_security][download][type] = "git"
projects[smile_security][download][tag]  = "7.x-1.1"
projects[smile_security][download][url]  = "http://gitlab.total.com/Smile/Security.git"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[facebook][download][type] = "get"
libraries[facebook][download][url] = "https://github.com/facebook/facebook-php-sdk-v4/archive/5.1.0.zip"
libraries[facebook][directory_name] = "facebook"
libraries[facebook][type] = "library"

libraries[twitter][download][type] = "get"
libraries[twitter][download][url] = "https://github.com/themattharris/tmhOAuth/archive/master.zip"
libraries[twitter][directory_name] = "twitter"
libraries[twitter][type] = "library"

libraries[jquery.imagesloaded][download][type] = "get"
libraries[jquery.imagesloaded][download][url] = "https://github.com/desandro/imagesloaded/archive/v2.1.2.tar.gz"
libraries[jquery.imagesloaded][directory_name] = "jquery.imagesloaded"
libraries[jquery.imagesloaded][type] = "library"

libraries[jquery.imgareaselect][download][type] = "get"
libraries[jquery.imgareaselect][download][url] = "http://odyniec.net/projects/imgareaselect/jquery.imgareaselect-0.9.10.zip"
libraries[jquery.imgareaselect][directory_name] = "jquery.imgareaselect"
libraries[jquery.imgareaselect][type] = "library"

libraries[jquery-cluetip-master][download][type] = "get"
libraries[jquery-cluetip-master][download][url] = "https://github.com/kswedberg/jquery-cluetip/archive/master.zip"
libraries[jquery-cluetip-master][directory_name] = "jquery-cluetip-master"
libraries[jquery-cluetip-master][type] = "library"

; Themes
projects[adminimal_theme][type]           = "theme"
projects[adminimal_theme][subdir]         = "contrib"
projects[adminimal_theme][version]        = "1.23"

